[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_anchor = "7ncy1ZWKme22jhAusPq1Ltk5AZuFJrJMqHFy2KPeosHz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/linh.tran/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
idl = "cp -r ./target/idl ./app/hui-web/contracts && cp -r ./target/types ./app/hui-web/contracts"
